.github/workflows/npm-publish.yml
package-lock.json
package.json
src/components/styled-table/editable-cell.tsx
src/components/utils/table.tsx
stories/components/styled-table/editable-cell.stories.tsx
test/components/styled-table/__snapshots__/cell-with-icon.test.tsx.snap
test/components/styled-table/__snapshots__/editable-cell.test.tsx.snap
test/components/styled-table/__snapshots__/header-cell.test.tsx.snap
test/components/styled-table/cell-with-icon.test.tsx
test/components/styled-table/editable-cell.test.tsx
test/components/styled-table/header-cell.test.tsx
test/it-tests/editable-cell-it.test.tsx

chore(npm): add npm publish github action

---

package-lock.json
package.json

chore(NPM): update version

---

package-lock.json
package.json

 chore(NPM): npm files field 

---

package-lock.json
package.json
tsconfig.json

TS compiler: use commonjs intead of esnext

chore(TS compiler): use commonjs intead of esnext

---

package-lock.json
package.json
tsconfig.json

fix(TS): ts compiler target to es5

---

package-lock.json
package.json
src/components/styled-table/header-cell.tsx
src/components/table/cell.tsx
src/style/styled-table/_header-cell.scss
src/style/table/_cell.scss
stories/components/styled-table/tables.ts
test/components/styled-table/__snapshots__/header-cell.test.tsx.snap
test/components/table/__snapshots__/cell.test.tsx.snap

chore(Header): fix header style

---

package-lock.json
package.json
src/components/table/row-span.tsx
src/style/table/_row.scss
test/components/table/__snapshots__/row-span.test.tsx.snap

chore(RowSpan): fix row span style

---

package-lock.json
package.json
src/components/styled-table/editable-cell.tsx
stories/components/styled-table/editable-cell.stories.tsx
test/components/styled-table/__snapshots__/editable-cell.test.tsx.snap
test/components/styled-table/editable-cell.test.tsx

Add disabled prop to the EditableCell component

chore(EditableCell): add disabled props

---

package-lock.json
package.json
src/components/table/row-span.tsx
src/components/table/row.tsx
stories/components/table-interactions-manager/table-interactions-manager.stories.tsx
test/components/table/__snapshots__/row-span.test.tsx.snap
test/components/table/__snapshots__/row.test.tsx.snap
test/it-tests/row-it.test.tsx
test/it-tests/virtualized-table.test.tsx
test/tests-utils/table.ts

test(tests): fix test ids props

---

package-lock.json
package.json
src/components/table-interactions-manager/table-interactions-manager.tsx
src/components/table/table.tsx
stories/components/table-interactions-manager/table-interactions-manager.stories.tsx
stories/components/table/table.stories.tsx
test/it-tests/rows-controller.test.tsx

add open/close rows controller
💔Thank you!

feat(rows): add open/close rows controller 

---

package-lock.json
package.json
src/components/table-interactions-manager/table-interactions-manager.tsx
src/components/table/row.tsx
src/components/table/table.tsx
src/hooks/index.ts
src/hooks/useComponent.ts
src/index.ts
stories/components/table-interactions-manager/table-interactions-manager.stories.tsx
test/it-tests/cell-dimensions-controller.test.tsx
test/it-tests/column-visibility-controller.test.tsx
test/it-tests/rows-controller.test.tsx

add the table state updateer
💔Thank you!

Feat add on table state update

---

package-lock.json
package.json
src/components/constants.ts
src/components/table-interactions-manager/actions.ts
src/components/table-interactions-manager/cell-dimensions-controller.tsx
src/components/table-interactions-manager/reducers.ts
src/components/table-interactions-manager/table-interactions-manager.tsx
stories/components/table-interactions-manager/table-interactions-manager.stories.tsx
test/components/table-interactions-manager/__snapshots__/cell-dimensions-controller.test.tsx.snap
test/components/table-interactions-manager/cell-dimensions-controller.test.tsx

add props to customize row height options and column width options in the cell-dimensions-controller component
💔Thank you!

feat(table interactions manager): add custom cell height and width options

---

package-lock.json
package.json
src/components/table-interactions-manager/column-visibility-controller.tsx
src/components/table/cell.tsx
src/components/table/elementary-table.tsx
src/components/table/row.tsx
src/style/table/_cell.scss
stories/components/table/table.stories.tsx
stories/utils/tables.ts
test/components/table/__snapshots__/cell.test.tsx.snap
test/components/table/__snapshots__/table.test.tsx.snap
test/components/table/cell.test.tsx
test/it-tests/column-visibility-controller.test.tsx

Add the columns and rows being read

feat(Table): Add the columns and rows being read

---

package-lock.json
package.json
src/components/table/cell.tsx
stories/components/table/table.stories.tsx
test/components/table/__snapshots__/cell.test.tsx.snap
test/components/table/cell.test.tsx

feat(cell): add dynamic class Name

---

package-lock.json
package.json
src/components/scroller.tsx
src/components/utils/table.tsx
src/components/virtualizer.tsx
stories/stories-components/selection-menu.tsx
test/components/__snapshots__/virtualizer.test.tsx.snap
test/components/table/utils.test.tsx
test/components/virtualizer.test.tsx
test/it-tests/virtualized-table.test.tsx

cleanup and refactoring, scroll management

Cleanup refactoring first commit

---

.eslintrc.js
package-lock.json
package.json
src/components/constants.ts
src/components/table/row-span.tsx
src/components/table/row.tsx
src/components/utils/table.tsx
src/style/table/_row-span.scss
test/components/table/__snapshots__/row.test.tsx.snap
test/components/table/utils.test.tsx

Fix rows height

---

package-lock.json
package.json
src/components/scroller.tsx
src/components/table-interactions-manager/table-interactions-manager.tsx
src/components/table/row.tsx
src/components/utils/table.tsx
src/components/virtualizer.tsx
stories/components/table/virtualized-table.stories.tsx
test/components/__snapshots__/scroller.test.tsx.snap
test/components/__snapshots__/virtualizer.test.tsx.snap
test/components/table/utils.test.tsx
test/components/virtualizer.test.tsx
test/it-tests/virtualized-table.test.tsx

chore(Virtualizer): fix adpated height and width

---

package-lock.json
package.json
src/components/styled-table/editable-cell.tsx
stories/components/styled-table/editable-cell.stories.tsx

select the editable cell value on focus

feat(Select): select the editable cell value on focus

---

package.json
src/style/table/_cell.scss

fix the min width of the cell wrapper

fix(cell): fix the min width of the cell wrapper

---

package-lock.json
package.json
src/components/table-interactions-manager/table-interactions-manager.tsx

Please describe your pull request.
💔Thank you!

chore(TableInteractionsManager): export interfaces

---

package.json
src/components/scroller.tsx
src/components/virtualizer.tsx
test/components/scroller.test.tsx

always handle onScroll
💔Thank you!

chore(scroll): always handle onScroll
